### ISSUE TITLE
The client cannot change the bound button

### ISSUE THREAD

**Issue by yebanme** [ASangarin/MythicKeys#1]
![image](https://user-images.githubusercontent.com/20102749/147905796-98d44d8e-d6db-47a1-bda4-14bb4beb3174.png)

After changing the hotkey, pressing the new hotkey will not trigger the effect, and the old hotkey is still valid

**Comment by ASangarin** [comment]
I take it you closed this because you... _fixed_ it?

**Comment by yebanme** [comment]
> I take it you closed this because you... _fixed_ it?

Yes, because I found it was my own problem, I was so excited when I began to try it
