### ISSUE TITLE
Event not firing

### ISSUE THREAD

**Issue by devJordanOfficial** [ASangarin/MythicKeys#2]
Hey there, I love the plugin/mod and would like to use it, however I have implemented the api using maven and adding the jar locally but the MythicKeyPressEvent isn't firing at all and I'm not sure if I've done something wrong or what is going on? Here is my code:
```
package fun.tbcraft.skillkeybinds;

import eu.asangarin.mythickeys.api.MythicKeyPressEvent;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;

public final class Main extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        // Plugin startup logic
        getServer().getPluginManager().registerEvents(this, this);
    }

    @Override
    public void onDisable() {
        // Plugin shutdown logic
    }

    @EventHandler
    public void onKeyPress(MythicKeyPressEvent event) {
        System.out.println("Event seen");
        Player player = event.getPlayer();
        if (event.getId().getKey().equals("healkey")) {
            player.setHealth(20);
            player.sendMessage("You have been healed!");
        }
    }
}
```

**Comment by ASangarin** [comment]
Which version of the plugin are you testing with?
And what version of the mod? There's been a lot of changes lately and mod/plugin versions need to match for anything to work.

**Comment by devJordanOfficial** [comment]
Oh that could be the issue then? I'm using the latest of both so 1.3 for the plugin and 1.2 for the mod. I will try installing 1.2 for the plugin and see what happens.

**Comment by ASangarin** [comment]
I have tested this and it seems to work on all latest versions.
Here is an example plugin that utilizes the event:
https://github.com/ASangarin/MythicKeysExample
